spring.application.name=jwtdemo
jwt.secret=VGhpc0lzTXlTdXBlclNlY3JldEtleUZvckpXVFRlc3RpbmcxMjM0NTY3ODkwMTIzNDU2Nzg5MA==
jwt.expiration=3600000

spring.datasource.url=jdbc:oracle:thin:@172.16.16.49:1521:fin
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=FG_DEMO_IR
spring.datasource.password=FG_DEMO_IR

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/jwt-demo
